### ISSUE TITLE
Composer dependency missing?

### ISSUE THREAD

**Issue by sydekumf** [php-http/discovery#107]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | no
| Version      | master

Just a quick question: In `Http\Discovery\Strategy\CommonClassesStrategy` you use classes i.e. `Nyholm\Psr7\Request` and this dependency is not defined in the `composer.json`. How does it work? This package composer.json states:
```
"require": {
        "php": "^5.5 || ^7.0"
    }
```

The Nyholm composer.json (https://github.com/Nyholm/psr7/blob/master/composer.json) states:
```
"require": {
        "php": "^7.1",
```

How can I use this package without conflicts and how is it supposed to be used when the dependencies are not explicitly declared? Thanks a lot guys.

**Comment by dbu** [comment]
@sydekumf maybe you already know, but if not then thats probably whats confusing to you: it is perfectly fine to `use Foo` and then have `Foo::class` even if such a class does not exist in your application. the class is only attempted to be loaded when you try to do something else with it. the ::class is called a "pseudo-constant" because its not really a field of the class but a language construct to get the fully qualified class name.

**Comment by sydekumf** [comment]
Hi guys, thanks a lot for that explanation! To be honest I did not know that it is the purpose of this lib to find out which implementation exists :-)
One more question: the autoloader tries to load these classes even if they are not used, how to deal with that?:
```
Warning: include(Nyholm\Psr7\Request.php): failed to open stream: No such file or directory...
```

**Comment by Nyholm** [comment]
You should not get such warning. 
What PHP version are you running? 
Is this vanilla PHP or are you using any framework or similar?
Are you using Magento?

**Comment by sydekumf** [comment]
It is Magento 1, yes. And idea how to use it in that combination?

**Comment by Nyholm** [comment]
No sorry. That is an issue with Magento. They are trying to create classes on `class_exists`. So with Magento, if you do `class_exists('FooFactory')`  you will an error like this instead of returning false. This is obviously a bug in Magento. 

It was discussed here: https://github.com/php-http/discovery/issues/105
I also tried to address the issue on Magento repo: https://github.com/magento/magento2/pull/14085

**Comment by sydekumf** [comment]
Lol, just read through it all :-) Had to laugh a lot, it seems not to be an easy issue. Thanks a lot @Nyholm for that information, helps me a lot!

**Comment by localheinz** [comment]
@Nyholm 

By any chance, do you have a suggestion for working around this issue?

**Comment by localheinz** [comment]
@Nyholm 

Ha, never mind!

**Comment by Nyholm** [comment]
@dbu would it make sense to add try/catch around our class_exists? 

I think that would work and it would help magento users. It is “weird php”...

**Comment by dbu** [comment]
actually yeah lets do that, with a comment what its for. doesn't cost us much and if magento believes in breaking things rather than following specs, we can help people here.
