### ISSUE TITLE
Support PSR-17

### ISSUE THREAD

**Issue by Taluu** [php-http/discovery#116]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | yes
| Version      | latest

#### Actual Behavior
It doesn't support PSR-17 factories

#### Expected Behavior
It should support PSR-17 factories (such as @Nyholm's psr-7 package, as the `httpplug` is already supported)

#### Possible Solutions
Allow to discover the psr-17 interfaces and the implementations that supports those (or at least the most popular ones, such as @Nyholm's psr-17 and zend diactoros - didn't look at the others)

**Comment by sagikazarmark** [comment]
Thanks, we are working on it.

**Comment by dbu** [comment]
in https://github.com/php-http/message/issues/105 we say we want to drop our own factories as they are superseeded by PSR-17. i think it makes sense to change this library to discover PSR-17 factories instead of httplug factories for its version 2.

HttpClientDiscovery should switch to discover a PSR-18 client, but HttpAsyncClientDiscovery would stay on Httplug because there is no PSR for asynchronous clients.
