### ISSUE TITLE
Change implementation of Puli Discovery

### ISSUE THREAD

**Issue by acinader** [php-http/discovery#117]
| Q            | A
| ------------ | ---
| Bug?         | no|
| New Feature? | no
| Version      | 1.4.0  9a6cb24  

I am using mailgun's php lib that depends on client discovery.

The following code is the first strategy tried and it'll always throw an exception since there is no stable puli implementation available, and from the looks of it, there never will be:

https://github.com/php-http/discovery/blob/9fcc4c99ecb457fa048dcca40fd452582288ba53/src/Strategy/PuliBetaStrategy.php#L36-L41

I like to keep 'break on exceptions' on in my IDE but this exception gets thrown in the normal course of its business, which is problematic.  I don't have any other libs that use this method of flow control (and if you're interested, I can make a good argument as to why it is a bad idea ;)).  

If you'd be open to a PR that either a) makes puli the second strategy instead of the first so no exeption gets thrown, b) removes the puli strategy, and/or c) changes the logic so an exception is only thrown if a strategy can't be found, I'd be glad to cook it up and submit it.

**Comment by sagikazarmark** [comment]
Other than a negligible performance hit I have no idea why exceptions as a means of flow control is a bad idea, so I would really be interested in that good argument.

For a long time Puli was our primary means of discovery because it can automagically wire services into your application without a single configuration file. But later on we decided to provide simpler mechanisms which turned out to be better, but Puli stayed there as an option.

In the meantime, you can easily set your own strategies if Puli bugs your eyes:
https://github.com/php-http/discovery/blob/master/src/ClassDiscovery.php#L117

**Comment by dbu** [comment]
the counter argument to that is that a method should not return two completely different things (an exception or the expected factory). from my understanding, exceptions are fine to be used in a control flow that way, but i am open for discussion.

looking out our code, changing to return instead of throw exceptions would not make the code harder to read or have the usual bad impact, as we immediately catch the exception and could instead check the return value.

however, changing this would be a BC break for all that implemented their own strategies. or we would need to both catch exceptions AND check the return type. that would become messy.

changing the order is not possible, as puli is the flexible, configurable thing. it has to come first, otherwise you would always get the first installed client with default configuration.

can you tell your IDE to ignore exceptions in that namespace so you can use your debugger the way you are used to? if not, there is a defined set of strategies that you can initialize with the setStrategies to not have the puli strategy in it.

if you are concerned about the performance, you should check if mailgun can be configured with the factories instead of using discovery at all. that would be the cleanest solution, discovery is only a convenience tool to reduce initial setup effort.

**Comment by acinader** [comment]
Thanks for the considered responses guys.  I appreciate the effort.

First off, I did figure out how to configure enough of discovery for the mailgun client that the exception now doesn't get thrown unless I am actually sending mail.  Initially, it was firing at injection which was unworkable.  So I can live with it now and given your thoughtful response, I'll close this issue as I don't think it is worth pursuing.

I did check the PHP Debugger in VS Code to see if I could disable the break for that class of exception but was unable too.

Performance is not a concern.

I buy your argument: 

> however, changing this would be a BC break for all that implemented their own strategies. or we would need to both catch exceptions AND check the return type. that would become messy.

If I were to continue to pursue this, I think I would try and change the upstream libs so I could configure this lib as you suggest without introducing a BC anywhere.

As for the style aspect of using exceptions here's an old post on the topic that covers it:

https://bit.ly/2LrNiaE

So my argument would be that this use violates the (Principle Of Least Astonishment)[https://web.archive.org/web/20140508144540/http://c2.com/cgi-bin/wiki?PrincipleOfLeastAstonishment] where the name Exception clearly shouldn't occur by default.  Certainly not compelling enough to make a BC.

This would be a good place for the use of an (Optional)[https://en.wikipedia.org/wiki/Option_type] if php had such a thing ;).

**Comment by sagikazarmark** [comment]
@acinader although I agree with your points about using exceptions, in this case I think it's an acceptable solution and as you also said, changing it probably isn't worth the BC break.

> `php-http/discovery` is several dependencies deep from the [mailgun php client](https://github.com/mailgun/mailgun-php) I am using and the `setStrategy` method of the `DiscoverClass` object is not exposed.

The method I linked is a public static method of a class, so you should be able to call it regardless what's exposed by the library.
