### ISSUE TITLE
PULI_FACTORY_CLASS ?

### ISSUE THREAD

**Issue by mowangjuanzi** [php-http/discovery#152]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | no
| Version      | 1.7.0

My monitoring system often shows the following errors:

```
Http\Discovery\Exception\PuliUnavailableException:Puli Factory is not available in vendor/php-http/discovery/src/Strategy/PuliBetaStrategy.php on line 40
```
I looked at where this error came from and found that it was because PULI_FACTORY_CLASS was not defined. Where is this constant defined?

**Comment by dbu** [comment]
when i look at https://github.com/php-http/discovery/blob/master/src/ClassDiscovery.php#L55-L57 i see that we try the strategies and if puli is not available, that triggers the exception, but we immediately catch it and only log it.

is your system breaking after that, or is your monitoring system configured to track exceptions in 3rd party libraries that do not bubble up to your application? if it is the later, you should tweak your monitoring, as it is expected behaviour that the exception is thrown and then caught.

**Comment by mowangjuanzi** [comment]
Yes. My anomaly monitoring tool is indeed a third party. So there are a lot of anomalies about this every hour. Thank you

**Comment by dbu** [comment]
you are welcome
