### ISSUE TITLE
"No PSR-17 request factory found" incorrectly suggests guzzlehttp/psr7

### ISSUE THREAD

**Issue by weaverryan** [php-http/discovery#164]
**PHP version**: 7.3

**Description**
Hi!

This seems related to #156 and #149.

I received the error: 

> No PSR-17 request factory found. Install a package from this list: https://packagist.org/providers/psr/http-factory-implementation

But when I go to https://packagist.org/providers/psr/http-factory-implementation, the first item on the list is `guzzlehttp/psr7`. When I installed it, I got the same error. After some deep digging, If found out that I actually needed `http-interop/http-factory-guzzle`. Installing that package *does* fix things - it's just the recommendation that was wrong (and tough to debug!).

Am I correct that `guzzlehttp/psr7` should not be shown on the list of "http factory implementations"? If so, why is it there? Is it a bug in *that* package's metadata? Something on Packagist? I don't know much about this - I'm just trying to get a bundle that is a few layers above this to work :).

Thanks!

**Comment by ste93cry** [comment]
>Am I correct that `guzzlehttp/psr7` should not be shown on the list of "http factory implementations"? If so, why is it there? Is it a bug in that package's metadata? Something on Packagist?

No you aren't: the `guzzlehttp/psr7` package is providing all PSR-17 factories but only starting from version `2.0.x-dev` which is currently in development (the [change](https://github.com/guzzle/psr7/blob/3472035ddb363a8452bc6999eeb92a92985879d7/composer.json#L39) is already in `master`), thus Packagist is correctly showing this package as a provider for the `psr/http-factory-implementation` virtual package. The error you got is due to the reason explained above: the version you have installed is not supporting PSR-17 and anyway the `php-http/discovery` package is not able to discover the newest version. I opened a PR to fix this, but if you want to stop requiring the `http-interop/http-factory-guzzle` package you will also have to update to an unstable version of the `guzzlehttp/psr7` package

**Comment by TomasVotruba** [comment]
This took me an hour to figure hour, painful WTF. The dev version packages should not be part of list that provide interface.

**Comment by dbu** [comment]
i am not exactly sure what you are reporting. afaik the only thing not tagged in php-http/discovery is the removal of puli. which should have been tagged, i am doing that now.

**Comment by TomasVotruba** [comment]
I'm sorry, this might not be related to your repository.

---

This one: https://github.com/php-http/discovery/issues/164#issuecomment-596015643

I'm not sure what repository this is, just reacted to the comments above which hold context shared with my problem.
