### ISSUE TITLE
Remove Puli CLI dependency

### ISSUE THREAD

**Issue by mishal** [php-http/discovery#41]
Please remove dependency on puli. We do not use it, nor symfony stuff. The dependency is too much for our project. I like the discovery for the adapters, but...

Reverting php-http/discovery back to 0.5 saves a lot of deps!

    - Removing padraic/phar-updater (dev-master)
    - Removing symfony/finder (2.8.x-dev)
    - Removing padraic/humbug_get_contents (dev-master)
    - Removing webmozart/console (dev-master)
    - Removing symfony/console (2.8.x-dev)
    - Removing symfony/polyfill-mbstring (dev-master)
    - Removing symfony/process (2.8.x-dev)
    - Removing psr/log (dev-master)
    - Removing ramsey/uuid (2.8.x-dev)
    - Removing symfony/event-dispatcher (2.8.x-dev)
    - Removing symfony/filesystem (2.8.x-dev)
    - Removing webmozart/expression (dev-master)
    - Removing webmozart/key-value-store (dev-master)
    - Removing webmozart/json (dev-master)
    - Removing seld/jsonlint (1.4.0)
    - Removing justinrainbow/json-schema (1.5.0)
    - Removing webmozart/glob (dev-master)
    - Removing webmozart/path-util (dev-master)
    - Removing webmozart/assert (dev-master)

**Comment by dbu** [comment]
discovery does not work without puli anymore. using it allowed us to remove most of our code that rebuilt what puli is doing.

looking at that list, i feel we should be conservative with any other things requiring discovery, however.

**Comment by sagikazarmark** [comment]
It not just allowed to remove most of our code, but puli is much more generic for the long-term as well. It allows us (and everyone) to improve package integration in ANY framework.

Of course it comes with a price: dependencies to be installed in every project, where the discovery is used.

**Comment by mishal** [comment]
I checked the ticket #28 but the depencency on puli is not acceptable for our project/s. To install those all packages just to make http client/message discovery is too much.

We decided to use your php-http packages beause they were simple and lightweight.. I know that only in alpa/beta stage...

Is there any chance to have separate branch without this dependency or does it mean we should create 0.5 compatible branch and use it instead of current code? Would it work in future with php-http/client-implementation?

We do not plan to use puli - we have asset packages managed by composer plugins and rails like asset pipeline.

**Comment by dbu** [comment]
@mishal you can totally use httplug, message and the adapters without discovery. discovery is just a cheap way of "service discovery" in php. we are currently working on the doc. see for example the upcoming guzzle 6 doc at https://github.com/php-http/documentation/pull/67 - works all fine without discovery.

**Comment by Nyholm** [comment]
I think the issue occurs when you use a library that depends on `php-http/discovery`. Say if you use `friendsofsymfony/http-cache` but inject your own client. You still need to download `puli/*` but you never use the discovery functionality.

**Comment by mishal** [comment]
Ok, thanks for explanation..

**Comment by webmozart** [comment]
The main problem here is not Puli, but the dependency on puli/cli. When that dependency is removed, a lot of the other transitive dependencies are gone as well.

**Comment by sagikazarmark** [comment]
Which gets us back to the beginning.

I have a really mad idea: In/Before Pul Composer plugin we should check if puli CLI is available. If not, download it to vendor/bin? This way we don't explicitly need puli/cli as dependency.

The other possibility is to bundle a puli.phar with the dependency package.

@mishal as @dbu said discovery actually provides service definitions in a highly opinionated way. Although it turned out that the massive dependency issue is caused by including the CLI, puli will still be a dependency nevertheless having cli as a dependency or not, but in the latter case there should be much lighter (which is our goal, having cli installed is only a temporary solution). Would that be acceptable by you?

**Comment by sagikazarmark** [comment]
Reopening the issue to solve the actual problem.

**Comment by webmozart** [comment]
> I have a really mad idea: In/Before Pul Composer plugin we should check if puli CLI is available. If not, download it to vendor/bin?

I had the same idea five minutes ago. Instead of vendor/bin, I'd download it to the project root though - just like composer.phar by default. Also, we should ask the user before we download.

**Comment by mishal** [comment]
It looks like that puli/repository-manager has still more then a few dependencies... :(

I need to check it a bit closer.

**Comment by webmozart** [comment]
@mishal That's a dependency of puli/cli and not needed if the CLI is not installed.

**Comment by sagikazarmark** [comment]
> Also, we should ask the user before we download.

What would happen if the user chooses not to download? Abort puli building process?

The advantage of having it in vendor/bin would be that it seems to be a common practice to add $CWD/vendor/bin to the $PATH. But it's almost the same as having it in the project root. Also, having it in the project root is probably makes it easier to find it.

**Comment by mishal** [comment]
@webmozart Sorry, I thought puli/puli is the right package to look at. Just checked that puli/puli is abandoned (-> puli/cli).

What package would be installed as dependency for the discovery?

**Comment by sagikazarmark** [comment]
```
        "puli/composer-plugin": "~1.0.0-beta8",
        "puli/discovery": "~1.0.0-beta8",
```

**Comment by webmozart** [comment]
@mishal np :) That would be puli/discovery. This package currently depends also on puli/repository, but I'd like to decouple the two. That means you'll only get three very tiny transitive dependencies:

* webmozart/assert
* webmozart/expression
* ramsey/uuid

**Comment by mishal** [comment]
that would be a step to a more lightweight solution than it is now :)

**Comment by webmozart** [comment]
See https://github.com/puli/issues/issues/164 and https://github.com/puli/issues/issues/165

**Comment by sagikazarmark** [comment]
Renamed the issue to reflect what we actually want: remove puli/cli dependency from the package as soon as puli CLI auto-download is implemented.

**Comment by sagikazarmark** [comment]
I think we all agreed that the CLI dependency must be removed from the project. I propose doing it right now with one of the following solutions:

- Temporarily add the latest puli phar in the project so that it is available.
- Create a separate repo&package for just the phar and recommend to always install that along with discovery. This way discovery is free to be installed in any packages without worrying future puli/cli stuff. If you want the puli cli, you have to install that or our puli.phar shim repo.
- Implement a quick composer plugin which downloads the puli.phar without asking

All the upper three solutions provide the same behavior as we have now with the cli package as a dependency. Once puli/issues#165 is implemented, projects are safe to remove our hacky solution and discovery can work as before.

WDYT?

**Comment by Nyholm** [comment]
Yes, Puli CLI is currently to heavy and cause us a lot of trouble. Since we are making a hacky solution that will be removed within 2 months I suggest we do the easiest thing possible. I think we should add the latest Puli.phar in the project.

**Comment by sagikazarmark** [comment]
#47

**Comment by sagikazarmark** [comment]
Composer dependency is now removed, added puli.phar instead to provide the same behavior.
