### ISSUE TITLE
Remove Puli Composer plugin dependency

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/discovery#49]
This has been discussed a few times now, but keeps coming back, so I open a new issue for this.

Generally, adding it as a dependency in a package is not recommended by @webmozart

It is also under discussion to make discovery optional everywhere, like in Guzzle 5:

https://github.com/php-http/guzzle5-adapter/blob/master/src/Client.php#L39

In this case, we would end up with two separate dependencies:

- Discovery
- Puli composer plugin

However, we could make discovery itself required dependency and only require to manually install the puli composer plugin.

**Comment by webmozart** [comment]
Just to provide some more extensive information: I recommend to move the Composer plugin from the required dependencies to the development dependencies because currently any other library that depends on Discovery will also install the Composer plugin, contain a .puli/ directory in development and a puli.json file, even if that library itself has no interest in Puli at all.

A less intrusive way is to recommend only end-user applications (those that actually inject a generated Puli Discovery service) to install the Composer plugin. Libraries that depend on Discovery can install the plugin in require-dev if they want - the important thing is that they have a choice.

**Comment by sagikazarmark** [comment]
Thanks for the input. Basically it is your second option is what I propose.

**Comment by joelwurtz** [comment]
:+1: for puli in require-dev, but need to had it everywhere we want to manage puli (not a big deal)
